---
name: dockerspart_build
on:
  #push:
  workflow_dispatch:

jobs:
  bloky_build_with_buildx_for_Prod:
    runs-on: ubuntu-latest
    steps:
    - name: checkout dockerspark repo
      uses: actions/checkout@v3
      with:
        repository: 'ktmrmshk/dockerspark'
        #ref: 'dnb_leeding_indicator'
        token: ${{ secrets.PAT }}
    
    - name: set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: set up docker buildx
      uses:  docker/setup-buildx-action@v2
      id:   buildx

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT}}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.actor }}/dockerspark:latest
        platforms: linux/amd64,linux/arm64
